### ISSUE TITLE
Range conditions.

### ISSUE THREAD

**Issue by slmyers** [yeg-relief/issue-tracker#1]
**use case:** 

> Is there a way to input an income query result as a range? I am working with the new Leisure Access Program and for people over the base amount but under another amount they will be eligible the Leisure Access Pass Lite. I would like to set it up so that for people eligible for the regular LAP they won’t see the Lite version (less confusing that way) but can’t seem to figure out how to set a minimum AND maximum income amount.

**requires:** 

1. Making a new condition type in Query object.
2. Building UI to support constructing such a condition.
3. testing the feature.

**Comment by farhadmak** [comment]
Moving to https://github.com/yeg-relief/youcanbenefit.
