### ISSUE TITLE
toggle questions

### ISSUE THREAD

**Issue by slmyers** [yeg-relief/issue-tracker#12]
toggle questions without a selection result in value `""` which seems to imply `true` in the backend for generating screener results.

**Comment by Lucase4c** [comment]
Hey Steven,

How much of an issue do you feel this is? I feel like it errs on the side of a false positive which is not a bad thing.

What do you think?


Lucas Stone e4c
Financial Empowerment Coordinator

LStone@e4calberta.org<mailto:LStone@e4calberta.org>
T       780.424.5408 x163
C       780.554.0894

9321 Jasper Avenue, Edmonton AB T5H 3T7

e4calberta.org<https://e4calberta.org/>

[cid:MainLogo_55796721-010e-435f-9c40-0dc1a644656e.png]

This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged and confidential. If you are not the intended recipient or the employee responsible for delivery of the message to the intended recipient, please be advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify us immediately by telephone and return the original email to us or destroy this message.

[cid:Environmentlogo_5cc24339-3bc0-40ee-87a1-6b0a51bb24dc.png]e4c supports environmental conservation - please print wisely.

**Comment by slmyers** [comment]
Well right now with 0 data filled on form you get a hit on ` Disability Tax Credit`. I'm not sure if this is ideal. 

Regardless, I feel like this is low priority -- even if it messes with results a bit. It is probably best for me to keep working on the style/presentation of the front end.

**Comment by slmyers** [comment]
toggle type is present in client app
