### ISSUE TITLE
back function breaks website

### ISSUE THREAD

**Issue by Lucase4c** [yeg-relief/issue-tracker#14]

**Comment by slmyers** [comment]
Can you give more details on this one? I can navigate with back, eg `/home` => `click browse` => `browser back` => `now I'm on /home`

**Comment by Lucase4c** [comment]
Huh, I thought we had talked about this as an issue before and for some reason my brain is still thinking it’s a problem. Guess not?

It’s working fine for me right now.


Lucas Stone e4c
Financial Empowerment Coordinator

LStone@e4calberta.org<mailto:LStone@e4calberta.org>
T       780.424.5408 x163
C       780.554.0894

9321 Jasper Avenue, Edmonton AB T5H 3T7

e4calberta.org<https://e4calberta.org/>

[cid:MainLogo_55796721-010e-435f-9c40-0dc1a644656e.png]

This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged and confidential. If you are not the intended recipient or the employee responsible for delivery of the message to the intended recipient, please be advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify us immediately by telephone and return the original email to us or destroy this message.

[cid:Environmentlogo_5cc24339-3bc0-40ee-87a1-6b0a51bb24dc.png]e4c supports environmental conservation - please print wisely.
