### ISSUE TITLE
About Section to be updated

### ISSUE THREAD

**Issue by Lucase4c** [yeg-relief/issue-tracker#16]
e4c name needs to be lowercase

Add City of Edmonton blurb

Add logos (if possible)

**Comment by slmyers** [comment]
about page redesigned. 

Need blurb from city and logos.

**Comment by Lucase4c** [comment]
Got it, will get on the City to get the logos and blurb. In the meantime do you want to add our logo to see how it looks?




Lucas Stone e4c
Financial Empowerment Coordinator

LStone@e4calberta.org<mailto:LStone@e4calberta.org>
T       780.424.7543 ext 123
C       780.554.0894

9321 Jasper Avenue, Edmonton AB T5H 3T7

e4calberta.org<https://e4calberta.org/>

[cid:MainLogo_55796721-010e-435f-9c40-0dc1a644656e.png]

This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged and confidential. If you are not the intended recipient or the employee responsible for delivery of the message to the intended recipient, please be advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify us immediately by telephone and return the original email to us or destroy this message.

[cid:Environmentlogo_5cc24339-3bc0-40ee-87a1-6b0a51bb24dc.png]e4c supports environmental conservation - please print wisely.

**Comment by slmyers** [comment]
Ok, i'll try. I'm also going to switch the order up so that I'm under the project description :D

**Comment by slmyers** [comment]
2-1-1 link will break page

**Comment by slmyers** [comment]
resolved
