### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by slmyers** [yeg-relief/issue-tracker#17]
navbar restyling

* make the active route standout
* investigate `md-sidenav` (side navigation) on smaller screens
* hide the admin link

**Comment by slmyers** [comment]
Ok, Admin link is now a little icon in the top right that is "hard to see". Once logged in you'll see links to the keys, programs and screener admin section of the site.

Added more navigation links to the user view. 
Made selected link black with a little checkmark in front of it.

**Comment by Lucase4c** [comment]
I like it a lot, Its easy to find if I am looking for it but doesn’t stand out for people using the tool.


Lucas Stone e4c
Financial Empowerment Coordinator

LStone@e4calberta.org<mailto:LStone@e4calberta.org>
T       780.424.7543 ext 123
C       780.554.0894

9321 Jasper Avenue, Edmonton AB T5H 3T7

e4calberta.org<https://e4calberta.org/>

[cid:MainLogo_55796721-010e-435f-9c40-0dc1a644656e.png]

This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged and confidential. If you are not the intended recipient or the employee responsible for delivery of the message to the intended recipient, please be advised that any dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify us immediately by telephone and return the original email to us or destroy this message.

[cid:Environmentlogo_5cc24339-3bc0-40ee-87a1-6b0a51bb24dc.png]e4c supports environmental conservation - please print wisely.
