### ISSUE TITLE
404.html

### ISSUE THREAD

**Issue by slmyers** [yeg-relief/issue-tracker#21]
need a nice `404.html`. We have one, but `Caddyserver` doesn't seem to want to show it.

**Comment by j-rewerts** [comment]
Looks like this right now.
<img width="1111" alt="screen shot 2018-09-28 at 2 09 22 pm" src="https://user-images.githubusercontent.com/8295080/46231190-3c258480-c328-11e8-9bd9-c057f9edd153.png">

**Comment by j-rewerts** [comment]
@dchenier You think this needs more work, or should we consider it resolved?

**Comment by dchenier** [comment]
@j-rewerts yeah, I think we can improve this, not too big of a priority though given our current workload.

**Comment by j-rewerts** [comment]
@farhadmak Might get you to look at this.

**Comment by farhadmak** [comment]
Moving to https://github.com/yeg-relief/youcanbenefit
